=== Oleksiy1984/LearnToCode/LearnToCode/src/xml/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:tns="http://nure.ua/your_last_name/SummaryTask3/entity"
	targetNamespace="http://nure.ua/your_last_name/SummaryTask3/entity"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="Gem">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="gem" type="tns:gem" minOccurs="1"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="gem">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="preciousness">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="Драгоценный" />
						<xsd:enumeration value="Полудрагоценный" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="origin" type="xsd:string" />
			<xsd:element name="visual_parameters" minOccurs="1"
					maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="color" type="xsd:string" />
						<xsd:element name="transparency">
							<xsd:simpleType>
								<xsd:restriction base="xsd:int">
									<xsd:minInclusive value="0" />
									<xsd:maxInclusive value="100" />
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="facets">
							<xsd:simpleType>
								<xsd:restriction base="xsd:int">
									<xsd:minInclusive value="4" />
									<xsd:maxInclusive value="45" />
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="value" type="xsd:double" />
		</xsd:sequence>
		<xsd:attribute name="id" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:ID">
					<xsd:pattern value="[a-zA-z0-9_]+" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>




</xsd:schema>

=== Oleksiy1984/LearnToCode/LearnToCode/src/xml/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<st7:Gem 
xsi:schemaLocation="http://nure.ua/your_last_name/SummaryTask3/entity input.xsd" 
xmlns:st7="http://nure.ua/your_last_name/SummaryTask3/entity" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<gem id="zm1">
		<name>Аметист</name>
		<preciousness>Полудрагоценный</preciousness>
		<origin>Мексика</origin>
		<visual_parameters>
			<color>Фиолетовый</color>
			<transparency>50</transparency>
			<facets>8</facets>
		</visual_parameters>
		<visual_parameters>
			<color>Фиолетовый2</color>
			<transparency>2</transparency>
			<facets>4</facets>
		</visual_parameters>
		<value>4</value>
	</gem>
	<gem id="cl1">
		<name>Изумруд</name>
		<preciousness>Драгоценный</preciousness>
		<origin>Африка</origin>
		<visual_parameters>
			<color>Зеленый</color>
			<transparency>40</transparency>
			<facets>12</facets>
		</visual_parameters>
		<value>2.8</value>
	</gem>
	<gem id="rub1">
		<name>Рубин</name>
		<preciousness>Драгоценный</preciousness>
		<origin>Азия</origin>
		<visual_parameters>
			<color>Красный</color>
			<transparency>60</transparency>
			<facets>30</facets>
		</visual_parameters>
		<value>3.6</value>
	</gem>
	<gem id="ait1">
		<name>Цитрин</name>
		<preciousness>Полудрагоценный</preciousness>
		<origin>Россия</origin>
		<visual_parameters>
			<color>Лимонный</color>
			<transparency>80</transparency>
			<facets>18</facets>
		</visual_parameters>
		<value>6.5</value>
	</gem>
</st7:Gem>
